import type { SalonConfig } from "../salon.types";

export const lekkoscConfig: SalonConfig = {
  slug: "lekkosc",
  brand: {
    name: "Lekkość",
    tagline: "Beauty Center · Kraków",
  },
  hero: {
    eyebrow: "Lekkość · Kraków",
    headline: "Pielęgnacja w jej najczystszej formie.",
    cta: "Umów wizytę",
  },
  about: {
    specialistName: "Yuliya Arutsiunian",
    role: "Założycielka",
    bio: "Lekkość powstała z potrzeby zwolnienia. Pracujemy w ciszy, bez pośpiechu, traktując każdy zabieg jako rytuał — precyzyjny, czuły, dopasowany do skóry. Skupiamy się na jednej osobie na raz.",
    signatureLine: "Yuliya Arutsiunian — założycielka",
  },
  specialists: [
    { id: "yuliya", name: "Yuliya Arutsiunian", role: "Założycielka, kosmetolog" },
  ],
  services: [
    {
      id: "oczyszczanie-wodorowe",
      name: "Oczyszczanie wodorowe",
      category: "twarz",
      price: 280,
      originalPrice: 350,
      durationMin: 90,
      shortDesc: "Głębokie oczyszczenie z technologią wodorową.",
    },
    {
      id: "peeling-kawitacyjny",
      name: "Peeling kawitacyjny",
      category: "twarz",
      price: 220,
      originalPrice: 280,
      durationMin: 75,
      shortDesc: "Delikatne złuszczanie ultradźwiękami.",
    },
    {
      id: "mezoterapia-iglowa",
      name: "Mezoterapia igłowa",
      category: "twarz",
      price: 450,
      originalPrice: 550,
      durationMin: 60,
      shortDesc: "Odżywienie skóry koktajlem aktywnych składników.",
    },
    {
      id: "mezoterapia-bezigłowa",
      name: "Mezoterapia bezigłowa",
      category: "twarz",
      price: 320,
      originalPrice: 400,
      durationMin: 60,
      shortDesc: "Nieinwazyjna regeneracja i nawilżenie.",
    },
    {
      id: "rf-mikroigłowy",
      name: "RF mikroigłowy",
      category: "twarz",
      price: 680,
      originalPrice: 850,
      durationMin: 90,
      shortDesc: "Liftingujący zabieg przebudowujący skórę.",
    },
    {
      id: "stylizacja-brwi",
      name: "Stylizacja brwi",
      category: "brwi-rzesy",
      price: 130,
      originalPrice: 160,
      durationMin: 45,
      shortDesc: "Regulacja, koloryzacja, laminacja.",
    },
    {
      id: "laminacja-brwi",
      name: "Laminacja brwi",
      category: "brwi-rzesy",
      price: 180,
      originalPrice: 220,
      durationMin: 60,
      shortDesc: "Trwałe ułożenie z pielęgnacją.",
    },
    {
      id: "laminacja-rzes",
      name: "Laminacja rzęs",
      category: "brwi-rzesy",
      price: 200,
      originalPrice: 250,
      durationMin: 75,
      shortDesc: "Naturalne podkręcenie z odżywieniem.",
    },
    {
      id: "makijaz-permanentny-brwi",
      name: "Makijaż permanentny brwi",
      category: "makijaz-permanentny",
      price: 1200,
      originalPrice: 1500,
      durationMin: 180,
      shortDesc: "Metoda piórkowa lub cieniowana.",
    },
    {
      id: "makijaz-permanentny-ust",
      name: "Makijaż permanentny ust",
      category: "makijaz-permanentny",
      price: 1400,
      originalPrice: 1700,
      durationMin: 180,
      shortDesc: "Subtelne podkreślenie linii i koloru.",
    },
    {
      id: "makijaz-permanentny-kreska",
      name: "Makijaż permanentny kreska",
      category: "makijaz-permanentny",
      price: 900,
      originalPrice: 1100,
      durationMin: 120,
      shortDesc: "Precyzyjna linia rzęs.",
    },
    {
      id: "rytual-pielegnacyjny",
      name: "Rytuał pielęgnacyjny",
      category: "pielegnacja",
      price: 380,
      originalPrice: 460,
      durationMin: 120,
      shortDesc: "Spersonalizowany zabieg sygnowany Lekkość.",
    },
    {
      id: "konsultacja-kosmetologiczna",
      name: "Konsultacja kosmetologiczna",
      category: "pielegnacja",
      price: 0,
      durationMin: 30,
      shortDesc: "Indywidualny plan pielęgnacji.",
    },
  ],
  gallery: [],
  experience: {
    pillars: [
      {
        eyebrow: "01",
        title: "Spokój",
        body: "Jedna klientka w gabinecie. Bez pośpiechu, bez rozmów na tle muzyki sklepu.",
      },
      {
        eyebrow: "02",
        title: "Precyzja",
        body: "Każdy ruch ma intencję. Sprzęt, kosmetyki i czas dobrane do skóry danego dnia.",
      },
      {
        eyebrow: "03",
        title: "Troska",
        body: "Słuchamy, zanim zaproponujemy. Plan pielęgnacji buduje się latami, nie w godzinę.",
      },
      {
        eyebrow: "04",
        title: "Rytuał",
        body: "Wizyta jest pauzą. Wchodzisz w jeden stan, wychodzisz w inny.",
      },
    ],
  },
  reviews: {
    booksy: { rating: 5.0, count: 69 },
    quotes: [
      {
        text: "Wreszcie miejsce, w którym czuję, że ktoś naprawdę słucha mojej skóry. Wychodzę inna niż wchodziłam.",
        author: "Anna · klientka od 2023",
      },
      {
        text: "Cisza, światło, gesty. Każdy szczegół przemyślany.",
        author: "Marta",
      },
      {
        text: "Najlepsza decyzja pielęgnacyjna ostatnich lat.",
        author: "Karolina",
      },
    ],
  },
  location: {
    addressLines: ["ul. Krzywa 8, L2"],
    city: "Kraków",
    postalCode: "31-149",
    country: "Polska",
    mapEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2562.0!2d19.9389!3d50.0681!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNTDCsDA0JzA1LjIiTiAxOcKwNTYnMjAuMCJF!5e0!3m2!1spl!2spl!4v1700000000000",
    hours: [
      { day: "Poniedziałek – Piątek", value: "10:00 – 20:00" },
      { day: "Sobota", value: "10:00 – 16:00" },
      { day: "Niedziela", value: "zamknięte" },
    ],
    parking: "Strefa płatnego parkowania. Postój taxi przy ul. Karmelickiej.",
    directionsUrl: "https://maps.google.com/?q=Krzywa+8+Kraków",
    geo: { lat: 50.0681, lng: 19.9389 },
  },
  contact: {
    phone: "+48 600 000 000",
    email: "kontakt@lekkosc.pl",
    instagram: "@lekkosc.krakow",
    instagramUrl: "https://instagram.com/lekkosc.krakow",
    booksyUrl: "https://booksy.com/",
  },
  seo: {
    title: "Lekkość · Beauty Center Kraków",
    description:
      "Kameralny gabinet kosmetologii w Krakowie. Pielęgnacja twarzy, stylizacja brwi i rzęs, makijaż permanentny.",
    locale: "pl_PL",
  },
};
